### ISSUE TITLE
Feature: User can view the categories 

### ISSUE THREAD

**Issue by Dustin-Davis** [Dustin-Davis/hyrule-compendium#1]
## ⚙️ Feature

> ##### What capability will users have when this feature is merged?

The user will be able to see all the categories displayed on the screen.

## 📐 Functionality

> ##### A description of how the application will work from the perspective of the user.

The user will be able to scroll up and down the page seeing the different objects on the page. 

## 🖼️ Wireframes

> ##### Wireframe screenshot(s) of what the app should look like when it is complete.

![Screenshot 2022-01-04 153036](https://user-images.githubusercontent.com/93169062/148137978-cbeca2bf-6246-4849-9f3e-bd74cd61ec9a.png)

## ✅ Task List

> ##### Commit checklist for tasks needed to complete the feature.

- [x] Have a NavBar displayed 
- [x] Have the objects on the nav be clickable  
- [x]  display the data from the API on the page 
- [x] Make sure that click targets are either `<a>` or `<button>` elements.
- [x] Make sure that all click targets show a `cursor: pointer` when hovered with the mouse.
- **Clean Up**
  - [x] Remove all buttons and placeholders that do not serve the functionality of the feature.
  - [x] Remove all console logs.
  - [x] Remove all commented out code.
  - [x] Remove all CSS properties that have no effect.
  - [x] Check all code for proper formatting and indentation.
  - [x] Confirm that there are no errors in the console while using the application.
  - [x] Confirm that all previous functionality still works without errors.
  - [x] Confirm that the user interface looks natural on both mobile and desktop screens.
  - [x] Create GIFs of the feature being used on both mobile and desktop screen sizes for inclusion in Pull Request.
